### PR TITLE
Add Scrollbars to Most Windows & Check-boxes to Toggle Options

### PR DESCRIPTION
**Pull request by rystills**
Adds scrollbars to main, opcodes, comments, changes, and phrases windows, allowing the user to navigate these windows via the scrollbar. Adds checkboxes to game entry point, hex mode, hex/bin separation, bin mode, base textbox, and status bar options. Adds option to disable save prompt on exit.

### CODE REVIEW

**Comment by rystills** [comment]
I didn't realize tk has checkbox functionality built-in. Will rectify this with another commit shortly.

**Comment by mitchasdf** [comment]
Hey! Sorry I didn't see the pull request. Nice work

**Comment by mitchasdf** [comment]
There was one little problem with one of your changes, just letting you know. Where you define updateToggleAddressLabel(), the iteration code you had within the noValue == True condition needed to be replaced with simply false. The only reason this is, is because pretty much none of my functions work unless disassembler_loaded() returns True. disasm.game_address_mode can be assumed False unless a ROM is loaded :)

Otherwise it throws an error (only if app_config['open_roms_automatically'] == False, or it is the very first time running the script) when running main.py

**Comment by rystills** [comment]
Good catch! I thought that case looked a bit suspicious, I just wasn't totally sure how the initial value of  disasm.game_address_mode should be handled. Glad it has been resolved :)

**Comment by mitchasdf** [comment]
Yeah, after some more thought, that case would only throw an error if it were the first time ever opening the script (app_config['game_address_mode'] is an empty dict at this point) or if the app config is deleted.

For disasm, it is declared initially, but is None, until the user loads a rom, that's when it is populated. When the user clicks open new rom and exits the open prompt or the file loaded isn't a ROM, disasm will be None again.

As for the jumps window, I think you can actually declare the scrollbars with the listbox as the master, instead of the jumps window, and when you use pack(), it ends up "attached" to the listbox

**Comment by mitchasdf** [comment]
So it might be a bit confusing why there is a game_address_mode for each individual rom the user has been editing. The way I wrote the code which memorises your functions you pressed Ctrl+G on was very sloppy. Instead of storing the integer for the address of the instruction, it stores the current offset state of the address. So when you toggle game address mode, it actually goes through and edits all of the jumps memorised so they have the correct offset again. I don't know why I made it this way. Lol. But if the game address mode is different to what it was when you last saved, it completely destroys that part of your app_config. All the data in the memorised functions would be offset by an additional amount.

**Pull request merged**
